name: Lamthong Keophalychanh
bio: 'Doing more of what makes me happy.'
picture: 

url: http://lamkeo.github.io/indigo
permalink: /:title/

analytics: 'UA-MYANALYTICS'
# disqus: mydisqus
# facebook: myfacebook
twitter: www.twitter.com/FatKidCaken
instagram: www.instagram.com/fatkidcaken
linkedin: www.linkedin.com/in/lamkeo
# youtube: myyoutube
# spotify: myspotify
github: www.github.com/lamkeo
email: thea913@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
