name: Lamthong Keophalychanh
bio: 'Doing more of what makes me happy.'
picture: '10432965_10153249699408566_6729131985319653915_n.jpg'

url: http://lamkeo.github.io/indigo
# permalink: /:title/

# analytics: 'UA-MYANALYTICS'
# disqus: mydisqus
# facebook: myfacebook
twitter: mytwitter
instagram: myinstagram
linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: mygithub
email: thea913@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
